{
 "title": "Atelier",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Checkouts declined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(checkouts_declined_total{ service_name=\"billing-service\"}[5m])) by (reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(checkouts_total{ service_name=\"billing-service\"}[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by (le) (rate(checkout_duration_milliseconds_bucket{ service_name=\"billing-service\"}[5m])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9,sum by (le) (rate(checkout_duration_milliseconds_bucket{ service_name=\"billing-service\"}[5m])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5,sum by (le) (rate(checkout_duration_milliseconds_bucket{ service_name=\"billing-service\"}[5m])))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Payment duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(payment_duration_milliseconds_bucket{ service_name=\"payment-service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Payment duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by (le) (rate(payment_duration_milliseconds_bucket{ service_name=\"payment-service\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9,sum by (le) (rate(payment_duration_milliseconds_bucket{ service_name=\"payment-service\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5,sum by (le) (rate(payment_duration_milliseconds_bucket{ service_name=\"payment-service\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Bank call duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (le) (rate(rpc_server_call_duration_seconds_bucket{ service_name=\"bank-service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Bank call duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by (le) (rate(rpc_server_call_duration_seconds_bucket{ service_name=\"bank-service\"}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9,sum by (le) (rate(rpc_server_call_duration_seconds_bucket{ service_name=\"bank-service\"}[$__rate_interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5,sum by (le) (rate(rpc_server_call_duration_seconds_bucket{ service_name=\"bank-service\"}[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    }
   ]
  }
 ]
}